cursor:
  style: Beam
  unfocused_hollow: false

font:
  normal:
    family: Fira Mono
    style: Regular
  bold:
    family: Fira Mono
    style: Bold
  italic:
    family: Fira Mono
    style: Italic
  bold_italic:
    family: Fira Mono
    style: Bold Italic
  size: 16
  offset:
    x: -1
    y: 4

import:
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
# acceptable themes: {wombat, Cobalt2}
  - ~/.config/alacritty/themes/themes/Cobalt2.yaml

window:
  dimensions:
    columns: 100
    lines: 40
  padding:
    x: 0
    y: 0
  opacity: 0.8

scrolling:
  history: 10000
