#!/bin/bash
# $ iwctl station wlan0 connect {SSID}
PACKAGES="
realtime-privileges sof-firmware
bash nano openssh wget git zip unzip unrar nmap htop rsync
intel-ucode vulkan-intel acpi bluez powertop
networkmanager nm-connection-editor network-manager-applet iwd
pipewire pipewire-pulse pipewire-jack pipewire-alsa pavucontrol
cups cups-pdf
ntfs-3g exfat-utils android-tools android-udev
terminus-font
sway wayland xorg-xwayland qt5-wayland brightnessctl mako slurp grim jq wl-clipboard waybar ttf-nerd-fonts-symbols
imv mpv rofi alacritty thunar file-roller polkit-gnome ffmpegthumbnailer
gimp krita inkscape blender pitivi audacity
firefox-developer-edition chromium youtube-dl code quassel-client discord telegram-desktop mumble dino
materia-gtk-theme materia-kde faenza-icon-theme kvantum-qt5 kvantum-theme-materia
ttf-droid ttf-roboto 
noto-fonts noto-fonts-extra noto-fonts-cjk
ttf-fira-code otf-fira-sans otf-fira-mono ttf-inconsolata
adobe-source-code-pro-fonts adobe-source-sans-pro-fonts adobe-source-serif-pro-fonts
archey3
gdm xfce4 xfce4-goodies plank
gnome gnome-tweaks
obs-studio libva-intel-driver
docker go rust hugo zola
"
AUR="
noto-fonts-emoji-blob ttf-roboto-slab ttf-amiri ttf-arabeyes-fonts ttf-qurancomplex-fonts ttf-sil-lateef ttf-sil-scheherazade
rofi-dmenu
gnome-shell-extension-dash-to-dock
enpass-bin xmousepasteblock-git
brother-mfc-7840w brscan3
checkra1n-cli
v4l2loopback-dkms
sublime-music
sanoid
"

sed -i '/#Color/s/^#//g' /etc/pacman.conf
sed -i '/#ParallelDownloads = 5/s/#ParallelDownloads = 5/ParallelDownloads = 20/g' /etc/pacman.conf

HOSTNAME=17z90p
USERNAME=trwnh

echo "Setting time sync..."
timedatectl set-ntp true

echo "Enabling archzfs..."
curl -s https://eoli3n.github.io/archzfs/init | bash

echo "Partitioning disk..."
sgdisk -Z /dev/nvme1n1
parted -s /dev/nvme1n1 mklabel gpt
sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"ESP" /dev/nvme1n1 \
       -n 2:0:+32G -t 2:8200 -c 2:"SWAP" /dev/nvme1n1 \
       -n 3:0:+2G -t 3:bf01 -c 3:"BPOOL" /dev/nvme1n1 \
       -n 4:0:0 -t 4:bf00 -c 4:"RPOOL" /dev/nvme1n1 \
sleep 3
partprobe /dev/nvme1n1
sleep 3

echo "Making legacy filesystems..."
mkfs.fat -F32 -n "EFI" /dev/disk/by-partlabel/ESP
mkswap -L "SWAP" /dev/disk/by-partlabel/SWAP

echo "Making bpool..."
#================ bpool with grub-compatible flags ================#
zpool create -f \
	-o ashift=12 \
	-o compatibility=grub2 \
	-O acltype=posixacl -O canmount=off -O compression=lz4 \
	-O devices=off -O normalization=formD -O relatime=on -O xattr=sa \
	-R /mnt -O mountpoint=/boot \
bpool /dev/disk/by-partlabel/BPOOL

echo "Making rpool..."
#================ rpool with compression and encryption ================#
zpool create -f \
	-o ashift=12              \
	-O acltype=posixacl       \
	-O relatime=on            \
	-O xattr=sa               \
	-O dnodesize=legacy       \
	-O normalization=formD    \
	-O mountpoint=none        \
	-O canmount=off           \
	-O devices=off            \
	-O compression=lz4        \
	-O encryption=aes-256-gcm \
	-O keyformat=passphrase   \
	-O keylocation=prompt     \
	-R /mnt                   \
rpool /dev/disk/by-partlabel/RPOOL

echo "Making ZFS datasets..."
#================================ boot environment = arch ================================#
zfs create -o canmount=off -o mountpoint=none bpool/BOOT
zfs create -o canmount=off -o mountpoint=none rpool/ROOT
zfs create -o canmount=off -o mountpoint=none rpool/DATA
zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/arch
zfs create -o canmount=noauto -o mountpoint=/     rpool/ROOT/arch
zpool set bootfs=rpool/ROOT/arch rpool
zfs mount rpool/ROOT/arch
zfs mount bpool/BOOT/arch
#================================ persistent data ================================#
zfs create -o mountpoint=/home rpool/DATA/home
zfs create -o mountpoint=/root rpool/DATA/home/root
chmod 700 /mnt/root
zfs create -o mountpoint=none                     rpool/DATA/var
zfs create -o mountpoint=/var/lib -o canmount=off rpool/DATA/var/lib
zfs create                                        rpool/DATA/var/lib/AccountsService
zfs create                                        rpool/DATA/var/lib/libvirt
zfs create                                        rpool/DATA/var/lib/lxc
zfs create                                        rpool/DATA/var/lib/portables
zfs create                                        rpool/DATA/var/lib/machines
zfs create                                        rpool/DATA/var/lib/pacman
zfs create -o com.sun:auto-snapshot=false         rpool/DATA/var/lib/docker
zfs create -o com.sun:auto-snapshot=false         rpool/DATA/var/lib/nfs
zfs create -o mountpoint=/var/log                 rpool/DATA/var/log
zfs create -o mountpoint=/var/spool               rpool/DATA/var/spool
zfs create                                        rpool/DATA/var/spool/mail
zfs create -o mountpoint=/var/snap                rpool/DATA/var/snap
zfs create -o mountpoint=/var/games               rpool/DATA/var/games
zfs create -o mountpoint=/var/www                 rpool/DATA/var/www
zfs create -o mountpoint=/srv                     rpool/DATA/srv
zfs create -o mountpoint=/opt                     rpool/DATA/opt
zfs create -o mountpoint=/usr -o canmount=off     rpool/DATA/usr
zfs create                                        rpool/DATA/usr/local
#================================ cache and temporary files ================================#
zfs create -o mountpoint=/var/cache -o com.sun:auto-snapshot=false rpool/DATA/var/cache
zfs create -o mountpoint=/var/tmp   -o com.sun:auto-snapshot=false rpool/DATA/var/tmp
zfs create -o mountpoint=/tmp       -o com.sun:auto-snapshot=false rpool/DATA/tmp
chmod 1777 /mnt/tmp
chmod 1777 /mnt/var/tmp
zpool set cachefile=/etc/zfs/zpool.cache rpool
mkdir -p /mnt/etc/zfs
cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache

#echo "Validating ZFS pool..."
#zpool export rpool
#zpool export bpool
#zpool import -d /dev/disk/by-id -R /mnt rpool -N
#zpool import -d /dev/disk/by-id -R /mnt bpool -N
#zfs load-key rpool
#zfs mount rpool/ROOT/arch
#zfs mount -a
#zfs mount bpool/BOOT/arch


echo -n "Mounting legacy filesystems... "
swapon -L "SWAP"
mkdir -p /mnt/boot/efi
mount -L "EFI" /mnt/boot/efi
echo "done."

echo "Updating pacman mirrorlist..."
pacman -Sy
pacman -S reflector --noconfirm
echo "Sorting mirrorlist..."
reflector --country 'US' -p https --sort rate --save /etc/pacman.d/mirrorlist --verbose
echo "Pacman mirrors synced and sorted."

echo "Bootstrapping mounted system..."
pacstrap /mnt base base-devel
VERSION=$(pacman -Si zfs-linux \
| grep 'Depends On' \
| sed "s|.*linux=||" \
| awk '{ print $1 }')
VERSION_LTS=$(pacman -Si zfs-linux-lts \
| grep 'Depends On' \
| sed "s|.*linux-lts=||" \
| awk '{ print $1 }')
if [ ${VERSION} = \
$(pacman -Si linux | grep Version | awk '{ print $3 }') ]; then
 pacstrap /mnt linux linux-headers
else
 pacstrap -U /mnt \
 https://archive.archlinux.org/packages/l/linux/linux-${VERSION}-x86_64.pkg.tar.zst \
 https://archive.archlinux.org/packages/l/linux/linux-headers-${VERSION}-x86_64.pkg.tar.zst
fi
if [ ${VERSION_LTS} = \
$(pacman -Si linux-lts | grep Version | awk '{ print $3 }') ]; then
 pacstrap /mnt linux-lts linux-lts-headers
else
 pacstrap -U /mnt \
 https://archive.archlinux.org/packages/l/linux-lts/linux-lts-${VERSION_LTS}-x86_64.pkg.tar.zst \
 https://archive.archlinux.org/packages/l/linux-lts/linux-lts-headers-${VERSION_LTS}-x86_64.pkg.tar.zst
fi
pacstrap /mnt zfs-linux zfs-linux-lts zfs-utils linux-firmware grub efibootmgr os-prober mkinitcpio
pacstrap /mnt $PACKAGES
echo "Packages installed."

echo -n "Generating filesystem mount table... "
genfstab -U /mnt >> /mnt/etc/fstab
echo "done."

echo -n "Setting hostname... "
echo "$HOSTNAME" > /mnt/etc/hostname
cat <<EOF > /mnt/etc/hosts
127.0.0.1 localhost
::1 localhost
127.0.1.1 $HOSTNAME.localdomain $HOSTNAME
EOF
arch-chroot /mnt hostnamectl set-hostname $HOSTNAME
echo "done."

echo "Localizing system..."
arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime
arch-chroot /mnt timedatectl set-timezone America/Chicago
echo "* Timezone set."
arch-chroot /mnt hwclock --systohc
echo "* Synced system clock to hardware clock."
echo "en_US.UTF-8 UTF-8
ar_JO.UTF-8 UTF-8" > /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
arch-chroot /mnt localectl set-locale en_US.UTF-8
echo "* Locale generated and applied."

echo "Avoid timeout -- press Enter when you are ready"
read TIMEOUT

echo "Setting up users..."
arch-chroot /mnt useradd -m -g users -G wheel,ftp,http,sys,audio,realtime,docker -s /bin/bash "$USERNAME"
echo "* Created user $USERNAME."
arch-chroot /mnt passwd $USERNAME
arch-chroot /mnt passwd
echo "* Set passwords."

echo -n "Enabling system services... "
arch-chroot /mnt /bin/bash <<EOF
systemctl enable NetworkManager
systemctl enable systemd-timesyncd
systemctl enable cups
systemctl enable gdm
EOF
echo "done."

echo -n "Changing configuration values... "
sed -i '/#Color/s/^#//g' /mnt/etc/pacman.conf
sed -i '/#ParallelDownloads = 5/s/#ParallelDownloads = 5/ParallelDownloads = 20/g' /mnt/etc/pacman.conf
sed -i '/#\s%wheel\sALL=(ALL)\sALL/s/^#//g' /mnt/etc/sudoers
echo "EDITOR=nano" > /mnt/etc/environment
echo "FONT=\"ter-v32b\"" > /mnt/etc/vconsole.conf
echo "SWEETHOME3D_JAVA3D=1.5" >> /mnt/etc/environment
sed -i "/\[multilib\]/,/Include/"'s/^#//' /mnt/etc/pacman.conf
echo "done."

echo "Installing AUR helper..."
arch-chroot /mnt /bin/bash <<EOF
git clone https://aur.archlinux.org/yay-bin.git
chmod -R 777 /yay-bin
cd /yay-bin
sudo -u $USERNAME makepkg -si --noconfirm
cd ..
rm -r /yay-bin
sudo -u $USERNAME yay --gendb
sudo -u $USERNAME yay --devel --nodiffmenu --save
exit
EOF

echo "Installing AUR packages..."
arch-chroot /mnt /bin/bash <<EOF
sudo -u $USERNAME yay -S $AUR
exit
EOF

lpadmin -p MFC7840W -E -v socket://192.168.1.15:9100 -P /usr/share/cups/model/MFC7840W.ppd



echo "Doing ZFS-y things..."
DISKID=nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NG0R621780A
echo GRUB_CMDLINE_LINUX=\"zfs_import_dir=${DISKID%/*}\" >> /mnt/etc/default/grub
sed -i 's/^HOOKS=\(.*\)/HOOKS=\(base udev autodetect modconf block keyboard zfs filesystems\)/g' /mnt/etc/mkinitcpio.conf
zgenhostid $(hostid)
systemctl enable zfs-import-scan.service zfs-import.target zfs-zed zfs.target --root=/mnt
#systemctl disable zfs-mount --root=/mnt
curl -L https://archzfs.com/archzfs.gpg |  pacman-key -a -
curl -L https://git.io/JsfVS | xargs -i{} pacman-key --lsign-key {}
curl -L https://git.io/Jsfw2 > /mnt/etc/pacman.d/mirrorlist-archzfs
echo "[archzfs]
Include = /etc/pacman.d/mirrorlist-archzfs
#[archzfs-testing]
#Include = /etc/pacman.d/mirrorlist-archzfs" >> /mnt/etc/pacman.conf
arch-chroot /mnt pacman -Sy

echo "Wait here"
read VERIFY

echo "Installing bootloader..."
arch-chroot /mnt /bin/bash <<EOF
rm -f /etc/zfs/zpool.cache
touch /etc/zfs/zpool.cache
chmod a-w /etc/zfs/zpool.cache
chattr +i /etc/zfs/zpool.cache
echo "GRUB_DISABLE_OS_PROBER=no" >> /mnt/etc/default/grub
echo 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3"' >> /mnt/etc/default/grub
echo "GRUB_GFXMODE=2560x1600" >> /mnt/etc/default/grub
mkdir -p /boot/efi/EFI/arch
grub-install --boot-directory /boot/efi/EFI/arch --efi-directory /boot/efi
ZPOOL_VDEV_NAME_PATH=YES grub-mkconfig -o /boot/efi/EFI/arch/grub/grub.cfg
mkdir -p /boot/grub
cp /boot/efi/EFI/arch/grub/grub.cfg /boot/grub/grub.cfg
EOF

echo "Did that work?"
read VERIFY

echo "Enabling Early KMS for GPU..."
sed -i 's/MODULES=\(\)/MODULES=(i915)/g' /mnt/etc/mkinitcpio.conf
arch-chroot /mnt /bin/bash <<EOF
mkinitcpio -p linux
mkinitcpio -p linux-lts
exit
EOF

echo "Taking snapshot of install..."
zfs snapshot -r rpool@install
zfs snapshot -r bpool@install

echo "Unmounting..."
sleep 5
umount /mnt/boot/efi
zfs umount -a
zpool export bpool
zpool export rpool

echo "Done! You may now reboot."
