#!/bin/bash

# PREPARATION:
# iwctl station wlan0 connect {SSID}

HOSTNAME=17z90p
USERNAME=a
TIMEZONE=America/Chicago
DISKID=nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NG0R621780A
DEV=/dev/disk/by-id/$DISKID
PACKAGES="
`#hardware support`
	intel-ucode vulkan-intel intel-media-driver acpi bluez powertop iwd fprint solaar
`#basic utilities`
	bash nano openssh wget rsync git zip unzip unrar nmap htop archey3 dnsutils bash-completion pacman-contrib
`#dev`
	docker docker-compose go rust hugo zola
`#networking`
	networkmanager ntpd
`#audio`
	pipewire wireplumber pipewire-pulse pipewire-jack pipewire-alsa sof-firmware realtime-privileges
`#files and devices`
	exfat-utils android-tools android-udev qmk samba nfs-utils
`#printer`
	cups cups-pdf sane-airscan
`#fonts`
	terminus-font
	ttf-droid ttf-roboto noto-fonts noto-fonts-extra noto-fonts-cjk
	ttf-fira-code otf-fira-sans otf-fira-mono
	ttf-inconsolata
	adobe-source-code-pro-fonts adobe-source-sans-pro-fonts adobe-source-serif-pro-fonts
	ttf-nerd-fonts-symbols
	ttf-dejavu
	inter-font
`#sway`
	sway
	wayland xorg-xwayland qt6-wayland qt5-wayland
	brightnessctl
	mako
	slurp grim jq wl-clipboard
	waybar
	imv mpv wofi alacritty
	thunar thunar-volman gvfs file-roller ffmpegthumbnailer
	zathura zathura-cb zathura-djvu zathura-pdf-mupdf
`#xfce`
	gdm xfce4 xfce4-goodies plank
`#gnome`
	gnome gnome-tweaks polkit-gnome gnome-shell-extension-appindicator
`#desktop`
	nm-connection-editor network-manager-applet pavucontrol
	firefox-developer-edition chromium yt-dlp
	quassel-client discord telegram-desktop mumble dino
	libva-intel-driver v4l2loopback-dkms
	gimp krita inkscape blender pitivi audacity
	bitwarden
	nextcloud-client nextcloud-client-cloudproviders python-nautilus trash-cli
	jre-openjdk sweethome3d
	curtail
	darktable rawtherapee shotwell
	texmaker texlive-most libreoffice-fresh
	steam lib32-vulkan-intel gnome-games libretro dolphin-emu mgba-qt
	transmission-remote-gtk
`#theming`
	materia-gtk-theme materia-kde faenza-icon-theme papirus-icon-theme kvantum kvantum-theme-materia
"
AUR="
`#more fonts`
	noto-fonts-emoji-blob ttf-roboto-slab
	ttf-amiri ttf-arabeyes-fonts ttf-qurancomplex-fonts ttf-sil-lateef ttf-scheherazade-new
`#more xfce`
	mugshot xfce4-docklike-plugin xmousepasteblock-git xfce4-windowck-plugin-xfwm4-theme-support `#vala-panel-appmenu-xfce is causing build errors`
`#more gnome`
	gnome-shell-extension-dash-to-dock chrome-gnome-shell
`#more desktop`
	enpass-bin sublime-music
	syncthing-gtk
	caffeine-ng
	visual-studio-code-bin
	obs-studio-tytan652
`#more printing`
	epson-inkjet-printer-escpr2
`#zfs snapshots and replication`
	sanoid lzop mbuffer pv
"

sed -i 's/^#Color/Color/g' /etc/pacman.conf
sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 10/' /etc/pacman.conf
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

echo "Setting time sync..."
timedatectl set-ntp true

echo "Enabling archzfs..."
curl -s https://eoli3n.github.io/archzfs/init | bash

echo "Partitioning disk..."
sgdisk -Z $DEV
parted -s $DEV mklabel gpt
sgdisk \
  -n 1:0:+32G -t 2:8200 -c 1:"SWAP" $DEV \
  -n 2:0:+2G -t 3:bf01 -c 2:"BPOOL" $DEV \
  -n 3:0:0 -t 4:bf00 -c 3:"RPOOL" $DEV
sleep 3
partprobe $DEV
sleep 3

echo "Making legacy filesystems..."
## reusing existing ESP, so line below is commented out
# mkfs.fat -F32 -n "EFI" /dev/disk/by-partlabel/ESP
mkswap -L "SWAP" /dev/disk/by-partlabel/SWAP

echo "Making bpool..."
#================ bpool with grub-compatible flags ================#
zpool create -f \
	-o ashift=12 \
	-o compatibility=grub2 \
	-O acltype=posixacl -O canmount=off -O compression=lz4 \
	-O devices=off -O normalization=formD -O relatime=on -O xattr=sa \
	-R /mnt -O mountpoint=/boot \
bpool /dev/disk/by-partlabel/BPOOL

echo "Making rpool..."
#================ rpool with compression and encryption ================#
zpool create -f \
	-o ashift=12              \
	-O acltype=posixacl       \
	-O relatime=on            \
	-O xattr=sa               \
	-O dnodesize=legacy       \
	-O normalization=formD    \
	-O mountpoint=none        \
	-O canmount=off           \
	-O devices=off            \
	-O compression=lz4        \
	-O encryption=aes-256-gcm \
	-O keyformat=passphrase   \
	-O keylocation=prompt     \
	-R /mnt                   \
rpool /dev/disk/by-partlabel/RPOOL

echo "Making ZFS datasets..."
#================================ boot environment = arch ================================#
zfs create -o canmount=off -o mountpoint=none bpool/BOOT
zfs create -o canmount=off -o mountpoint=none rpool/ROOT
zfs create -o canmount=off -o mountpoint=none rpool/DATA
zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/arch
zfs create -o canmount=noauto -o mountpoint=/     rpool/ROOT/arch
zpool set bootfs=rpool/ROOT/arch rpool
zfs mount rpool/ROOT/arch
zfs mount bpool/BOOT/arch
#================================ persistent data ================================#
zfs create -o mountpoint=/home rpool/DATA/home
zfs create -o mountpoint=/root rpool/DATA/home/root
chmod 700 /mnt/root
zfs create -o mountpoint=none                     rpool/DATA/var
zfs create -o mountpoint=/var/lib -o canmount=off rpool/DATA/var/lib
zfs create                                        rpool/DATA/var/lib/AccountsService
zfs create                                        rpool/DATA/var/lib/libvirt
zfs create                                        rpool/DATA/var/lib/lxc
zfs create                                        rpool/DATA/var/lib/portables
zfs create                                        rpool/DATA/var/lib/machines
zfs create                                        rpool/DATA/var/lib/pacman
zfs create -o com.sun:auto-snapshot=false         rpool/DATA/var/lib/docker
zfs create -o com.sun:auto-snapshot=false         rpool/DATA/var/lib/nfs
zfs create -o mountpoint=/var/log                 rpool/DATA/var/log
zfs create -o mountpoint=/var/spool               rpool/DATA/var/spool
zfs create                                        rpool/DATA/var/spool/mail
zfs create -o mountpoint=/var/snap                rpool/DATA/var/snap
zfs create -o mountpoint=/var/games               rpool/DATA/var/games
zfs create -o mountpoint=/var/www                 rpool/DATA/var/www
zfs create -o mountpoint=/srv                     rpool/DATA/srv
zfs create -o mountpoint=/opt                     rpool/DATA/opt
zfs create -o mountpoint=/usr -o canmount=off     rpool/DATA/usr
zfs create                                        rpool/DATA/usr/local
#================================ cache and temporary files ================================#
zfs create -o mountpoint=/var/cache -o com.sun:auto-snapshot=false rpool/DATA/var/cache
zfs create -o mountpoint=/var/tmp   -o com.sun:auto-snapshot=false rpool/DATA/var/tmp
zfs create -o mountpoint=/tmp       -o com.sun:auto-snapshot=false rpool/DATA/tmp
chmod 1777 /mnt/tmp
chmod 1777 /mnt/var/tmp

#echo "Validating ZFS pool..."
#zpool export rpool
#zpool export bpool
#zpool import -d /dev/disk/by-id -R /mnt rpool -N
#zpool import -d /dev/disk/by-id -R /mnt bpool -N
#zfs load-key rpool
#zfs mount rpool/ROOT/arch
#zfs mount -a
#zfs mount bpool/BOOT/arch


echo -n "Mounting legacy filesystems... "
swapon -L "SWAP"
mkdir -p /mnt/boot/efi
mount -L "EFI" /mnt/boot/efi
echo "done."

echo "Updating pacman mirrorlist..."
pacman -Sy
pacman -S reflector --noconfirm
echo "Sorting mirrorlist..."
reflector --country 'US' -p https --sort rate --save /etc/pacman.d/mirrorlist --verbose
echo "Pacman mirrors synced and sorted."

echo "Bootstrapping mounted system..."
pacstrap /mnt base base-devel
VERSION=$(pacman -Si zfs-linux \
| grep 'Depends On' \
| sed "s|.*linux=||" \
| awk '{ print $1 }')
VERSION_LTS=$(pacman -Si zfs-linux-lts \
| grep 'Depends On' \
| sed "s|.*linux-lts=||" \
| awk '{ print $1 }')
if [ ${VERSION} = \
$(pacman -Si linux | grep Version | awk '{ print $3 }') ]; then
 pacstrap /mnt linux linux-headers
else
 pacstrap -U /mnt \
 https://archive.archlinux.org/packages/l/linux/linux-${VERSION}-x86_64.pkg.tar.zst \
 https://archive.archlinux.org/packages/l/linux/linux-headers-${VERSION}-x86_64.pkg.tar.zst
fi
if [ ${VERSION_LTS} = \
$(pacman -Si linux-lts | grep Version | awk '{ print $3 }') ]; then
 pacstrap /mnt linux-lts linux-lts-headers
else
 pacstrap -U /mnt \
 https://archive.archlinux.org/packages/l/linux-lts/linux-lts-${VERSION_LTS}-x86_64.pkg.tar.zst \
 https://archive.archlinux.org/packages/l/linux-lts/linux-lts-headers-${VERSION_LTS}-x86_64.pkg.tar.zst
fi
pacstrap /mnt zfs-linux zfs-linux-lts zfs-utils linux-firmware grub efibootmgr os-prober mkinitcpio
pacstrap /mnt $PACKAGES
echo "Packages installed."

echo -n "Generating filesystem mount table... "
#genfstab -U /mnt >> /mnt/etc/fstab
cat <<EOF > /mnt/etc/fstab
LABEL=EFI /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 2
LABEL=SWAP none swap defaults 0 0
EOF
echo "done."

echo -n "Setting hostname... "
echo "$HOSTNAME" > /mnt/etc/hostname
cat <<EOF > /mnt/etc/hosts
127.0.0.1 localhost
::1 localhost
127.0.1.1 $HOSTNAME.localdomain $HOSTNAME
EOF
arch-chroot /mnt hostnamectl set-hostname $HOSTNAME
echo "done."

echo "Localizing system..."
arch-chroot /mnt ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
arch-chroot /mnt timedatectl set-timezone $TIMEZONE
echo "* Timezone set."
arch-chroot /mnt hwclock --systohc
echo "* Synced system clock to hardware clock."
cat <<EOF > /mnt/etc/locale.gen
en_US.UTF-8 UTF-8
ar_JO.UTF-8 UTF-8
EOF
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
arch-chroot /mnt localectl set-locale en_US.UTF-8
echo "* Locale generated and applied."

echo "Avoid timeout -- press Enter when you are ready"
read TIMEOUT

echo "Setting up users..."
zfs create rpool/DATA/home/$USERNAME
arch-chroot /mnt useradd -m -g users -G wheel,ftp,http,sys,audio,realtime,docker -s /bin/bash "$USERNAME"
arch-chroot /mnt chown -R $USERNAME:users /home/$USERNAME
echo "* Created user $USERNAME."
arch-chroot /mnt passwd $USERNAME
arch-chroot /mnt passwd
echo "* Set passwords."

echo -n "Enabling system services... "
systemctl enable NetworkManager --root=/mnt
systemctl enable systemd-timesyncd --root=/mnt
systemctl enable cups --root=/mnt
systemctl enable bluetooth --root=/mnt
systemctl enable gdm --root=/mnt
echo "done."

echo -n "Changing configuration values... "
sed -i 's/^#Color/Color/g' /mnt/etc/pacman.conf
sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 20/' /mnt/etc/pacman.conf
sed -i "/\[multilib\]/,/Include/"'s/^#//' /mnt/etc/pacman.conf
echo '%wheel      ALL=(ALL) ALL' > /mnt/etc/sudoers.d/wheel
echo "FONT=\"ter-v32b\"" > /mnt/etc/vconsole.conf
cat <<EOF > /mnt/etc/environment
EDITOR=nano
SWEETHOME3D_JAVA3D=1.5
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCALE_FACTOR=1
EOF
echo "done."

echo "Installing AUR helper..."
arch-chroot /mnt /bin/bash <<EOF
git clone https://aur.archlinux.org/yay-bin.git
chmod -R 777 /yay-bin
cd /yay-bin
sudo -u $USERNAME makepkg -si --noconfirm
cd ..
rm -r /yay-bin
sudo -u $USERNAME yay --gendb
sudo -u $USERNAME yay --devel --nodiffmenu --save
exit
EOF

echo "Installing AUR packages..."
arch-chroot /mnt /bin/bash <<EOF
sudo -u $USERNAME yay -S $AUR
exit
EOF

echo "Doing ZFS-y things..."
sed -i 's/^HOOKS=\(.*\)/HOOKS=\(base udev autodetect modconf block keyboard zfs filesystems\)/g' /mnt/etc/mkinitcpio.conf
zgenhostid $(hostid)
systemctl enable zfs-import-scan zfs-import-cache zfs-import.target zfs-zed zfs.target --root=/mnt
systemctl enable zfs-mount --root=/mnt
curl -L https://archzfs.com/archzfs.gpg |  pacman-key -a -
curl -L https://git.io/JsfVS | xargs -i{} pacman-key --lsign-key {}
curl -L https://git.io/Jsfw2 > /mnt/etc/pacman.d/mirrorlist-archzfs
echo "[archzfs]
Include = /etc/pacman.d/mirrorlist-archzfs
#[archzfs-testing]
#Include = /etc/pacman.d/mirrorlist-archzfs" >> /mnt/etc/pacman.conf
arch-chroot /mnt pacman -Sy
echo 'export ZPOOL_VDEV_NAME_PATH=1' >> /mnt/etc/profile.d/zfs.sh
echo 'Defaults env_keep += "ZPOOL_VDEV_NAME_PATH"' > /mnt/etc/sudoers.d/zfs
arch-chroot /mnt /bin/bash <<EOF
mkdir /etc/zfs/zfs-list.cache
touch /etc/zfs/zfs-list.cache/bpool
touch /etc/zfs/zfs-list.cache/rpool
#ln -s /usr/lib/zfs-linux/zed.d/history_event-zfs-list-cacher.sh /etc/zfs/zed.d
zed -F &
zfs set canmount=noauto bpool/BOOT/arch
zfs set canmount=noauto rpool/ROOT/arch
EOF

echo "Wait here"
read VERIFY

echo "Installing bootloader..."
arch-chroot /mnt /bin/bash <<EOF
#echo 'GRUB_CMDLINE_LINUX=\"zfs_import_dir=${DISKID%/*}\"' >> /etc/default/grub
echo "GRUB_DISABLE_OS_PROBER=no" >> /etc/default/grub
echo 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 video=2560x1600"' >> /etc/default/grub
echo "GRUB_GFXMODE=2560x1600" >> /etc/default/grub
echo "GRUB_DEFAULT=saved" >> /etc/default/grub
echo "GRUB_SAVEDEFAULT=true" >> /etc/default/grub
sed -i "s|rpool=.*|rpool=\`zdb -l \${GRUB_DEVICE} \| grep -E '[[:blank:]]name' \| cut -d\\\' -f 2\`|"  /etc/grub.d/10_linux
sed -i "s|^  linux=.*|  linux=\`echo \$list \| tr ' ' '\\\n' \| sort -V \| head -1 \| cat\`|" /etc/grub.d/10_linux
mkdir -p /boot/efi/EFI/arch
echo 'export ZPOOL_VDEV_NAME_PATH=1' >> /etc/profile.d/zpool_vdev_name_path.sh
ZPOOL_VDEV_NAME_PATH=1 grub-install --boot-directory /boot/efi/EFI/arch --efi-directory /boot/efi
ZPOOL_VDEV_NAME_PATH=1 grub-mkconfig -o /boot/efi/EFI/arch/grub/grub.cfg
mkdir -p /boot/grub
cp /boot/efi/EFI/arch/grub/grub.cfg /boot/grub/grub.cfg
EOF

echo "Did that work?"
read VERIFY

echo "Enabling Early KMS for GPU..."
sed -i 's/^MODULES=.*/MODULES=(i915)/' /mnt/etc/mkinitcpio.conf
arch-chroot /mnt /bin/bash <<EOF
mkinitcpio -P
exit
EOF

echo "Installing vala-panel-appmenu-xfce from AUR because building it fails..."
arch-chroot /mnt /bin/bash <<EOF
cd /home/$USERNAME/
mkdir -p build
cd build
sudo -u $USERNAME yay -G vala-panel-appmenu
cd vala-panel-appmenu
sed -i '/_disable_mate=false/s/false/true/' PKGBUILD
sed -i '/_disable_vala=false/s/false/true/' PKGBUILD
sed -i '/_disable_budgie=false/s/false/true/' PKGBUILD
sudo -u $USERNAME makepkg -sic --noconfirm
EOF

echo "Setting up printers..."
lpadmin -p "ET-3850" \
	-D "Epson ET-3850" \
	-L "Downstairs" \
	-v lpd://192.168.1.15:515/PASSTHRU \
	-P /usr/share/ppd/epson-inkjet-printer-escpr2/Epson-ET-3850_Series-epson-escpr2-en.ppd \
	-E
lpadmin -p "CUPS-PDF" \
	-D "Virtual PDF printer" \
	-L "$HOSTNAME" \
	-v cups-pdf:/ \
	-P /usr/share/cups/model/CUPS-PDF_opt.ppd \
	-E

echo "Taking snapshot of install..."
zpool set cachefile=/etc/zfs/zpool.cache bpool
zpool set cachefile=/etc/zfs/zpool.cache rpool
mkdir -p /mnt/etc/zfs
cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache
zfs snapshot -r rpool@install
zfs snapshot -r bpool@install

echo "Unmounting..."
sleep 5
umount /mnt/boot/efi
zfs umount -a
zpool export bpool
zpool export rpool

echo "Done! You may now reboot."

# UNHANDLED STUFF

## NTFS kernel driver fix
## sed -i '' /etc/udisks2/mount_options.conf
##
## [defaults]
## ntfs_defaults=uid=$UID,gid=$GID,prealloc

