#!/bin/bash
# for a graphical desktop. don't run this, etc

## XFCE
sudo pacman -S xorg xorg-server
sudo pacman -S xfce4 xfce4-goodies
echo "exec startxfce4" >> .bash_profile

## Fonts -- pick and choose
yay -S all-repository-fonts
# --- bitmap ---
# packer -S proggyfonts bdf-unifont terminus-font profont
# --- families ---
# packer -S ttf-bitstream-vera ttf-dejavu ttf-liberation ttf-ubuntu-font-family
#           ttf-croscore ttf-courier-prime ttf-google-fonts ttf-droid ttf-roboto noto-fonts
# --- monospace ---
# packer -S ttf-anonymous-pro otf-fira-mono ttf-freefont
#           ttf-hack ttf-inconsolata ttf-inconsolata-g
#           ttf-meslo ttf-monaco ttf-monofur ttf-mononoki
#           adobe-source-code-pro-fonts
# --- arabic ---
# packer -S ttf-amiri ttf-arabeyes-fonts ttf-qurancomplex-fonts
#           ttf-sil-lateef ttf-sil-scheherazade

## 
