#!/bin/bash
# syntax highlighting, you know the drill

## Install some other utilities, if you didn't already
sudo pacman -S wget unzip zip unrar rsync
               archey3 # neofetch screenfetch

## Python 
sudo pacman -S python

## zsh
yay -S zsh oh-my-zsh-git
       powerline otf-inconsolata-powerline-git
       zsh-theme-powerlevel9k
       zsh-autosuggestions
curl https://raw.githubusercontent.com/trwnh/arch/master/config/.zshrc > ~/.zshrc
