#!/bin/bash
# stuff after install. don't run this either

## User management
# (login as root)
useradd -m                          # create new user
        -g users                    # in users group
        -s /bin/bash                # with bash as default shell
        trwnh                       # username
usermod -aG wheel,http,ftp trwnh    # append groups to user
passwd trwnh                        # set password for new user
nano /etc/sudoers                   # uncomment wheel, ctrl+x, y, [enter]
echo "EDITOR=nano" > /etc/environment
exit
# (log in as new non-root user)

## Install an AUR helper
### packer (incredibly basic and written in bash, but stalled development)
# sudo pacman -S wget git expac jshon                                         # dependencies
# mkdir packer && cd packer                                                   # create and enter a directory
# sudo wget -O PKGBUILD                                                       # download PKGBUILD script
#           https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=packer
# makepkg                                                                     # make package
# sudo pacman -U packer- [tab to autocomplete] [enter]                        # install package from local build
# cd .. && sudo rm -dR packer                                                 # exit directory and cleanup
### yay (if you're willing to have Go installed as a dependency during build)
sudo pacman -S git                                                            # dependency for build
git clone https://aur.archlinux.org/yay.git                                   # clone the repo
cd yay && makepkg -sic                                                        # (s)ync deps, (i)nstall pkg, (c)lean files
yay --nodiffmenu --save                                                       # if you never want to see diffs 
# yay -Yc    # clean unneeded dependencies (like Go, maybe)
# yay -Ps    # (P)rint (s)tatistics
cat "Color" >> /etc/pacman.conf

## Network time
sudo systemctl start systemd-timesyncd
sudo systemctl enable systemd-timesyncd
# timedatectl    # if you want to check

## Virtualbox Guest Utilities, if running inside VBox
sudo pacman -S linux-headers virtualbox-guest-modules-arch
sudo pacman -S virtualbox-guest-utils                        # for graphical system
# sudo pacman -S virtualbox-guest-utils-nox                  # for non-graphical system
sudo systemctl start vboxservice
sudo systemctl enable vboxservice
